spring:
    application:
        name: EnNote
#    security:
#        user:
#            name: akash
#            password: akash
    datasource:
        url: jdbc:mysql://localhost:3306/ennote
        username: root
        password: "@@Akash@2003"
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    app:
        jwtSecret: "a6eac1a0ae42d3e466b45dd4610e18decdb339b59bda075853ae0229fd4edc35"
        jwtExpirationMs: "172800000"
logging:
    level:
        org:
            springframework:
                security: debug
        root: info

