spring:
    application:
        name: EnNote
#    security:
#        user:
#            name: akash
#            password: akash
    datasource:
        url: jdbc:mysql://localhost:3306/ennote
        username: root
        password: "@@Akash@2003"
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
logging:
    level:
        org:
            springframework:
                security: info
        root: info

